# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/2 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositório
      uses: actions/checkout@v3  # Updated to use a newer version

    - name: Configurar Ambiente Virtual
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip  # Upgrade pip within the virtual environment

    - name: Instalando Dependências Python
      run: |
        source venv/bin/activate
        pip install streamlink selenium requests beautifulsoup4 lxml python-dateutil yt-dlp youtube-dl pytz

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg      

    - name: Delete log
      run: |
        rm -rf ./log.txt

    - name: Main
      run: |
        chmod +x generate.sh
        ./generate.sh

    - name: git pull
      run: |
        git pull origin main

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
